language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  - PHPUNIT_VERSION=dev-master
  - PHPUNIT_VERSION=~4.4.0
  - PHPUNIT_VERSION=~4.3.0
  - PHPUNIT_VERSION=~4.2.0
  - PHPUNIT_VERSION=~4.1.0
  - PHPUNIT_VERSION=~4.0.0

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - composer require phpunit/phpunit:${PHPUNIT_VERSION}
  - composer require squizlabs/php_codesniffer
  - composer require phpmd/phpmd

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 classes/ tests/
  - vendor/bin/phpmd classes/ text cleancode,codesize,controversial,design,naming,unusedcode

